#!/usr/bin/env python3
# -*- coding:utf-8 -*-
# @Author:      thepoy
# @Email:       thepoy@163.com
# @File Name:   ns.pyi
# @Created At:  2023-03-20 18:30:24
# @Modified At: 2023-03-20 18:34:47
# @Modified By: thepoy

nsmap: dict[str, str]
pfxmap: dict[str, str]

class NamespacePrefixedTag(str):
    def __init__(self, nstag: str) -> None: ...
    @property
    def clark_name(self) -> str: ...
    @classmethod
    def from_clark_name(cls, clark_name: str) -> NamespacePrefixedTag: ...
    @property
    def local_part(self) -> str: ...
    @property
    def nsmap(self) -> dict[str, str]: ...
    @property
    def nspfx(self) -> str: ...
    @property
    def nsuri(self) -> str: ...

def nsdecls(*prefixes: str) -> str: ...
def nspfxmap(*nspfxs: str) -> dict[str, str]: ...
def qn(tag: str) -> str: ...
